# Generated by Django 5.1.4 on 2025-01-13 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='owner',
            new_name='user',
        ),
    ]
